// Vercel serverless entry. Adapts Node IncomingMessage/ServerResponse to the
// Web Fetch API handler exposed by TanStack Start (dist/server/server.js).
//
// Vercel's Node.js runtime invokes the default export with (req, res) — Node
// style — not the Web Standards (request) => Response signature. We translate
// here so the SSR handler receives a real Request with an absolute URL.

import type { IncomingMessage, ServerResponse } from "node:http";
import { Readable } from "node:stream";

// @ts-ignore - generated by `vite build` at deploy time
import server from "../dist/server/server.js";

export const config = { runtime: "nodejs" };

const ssr = (server as { fetch: (req: Request) => Promise<Response> }).fetch;

export default async function handler(req: IncomingMessage, res: ServerResponse) {
  const protocol = (req.headers["x-forwarded-proto"] as string | undefined) ?? "https";
  const host = req.headers.host ?? "localhost";
  const url = `${protocol}://${host}${req.url ?? "/"}`;

  const headers = new Headers();
  for (const [key, value] of Object.entries(req.headers)) {
    if (Array.isArray(value)) {
      for (const v of value) headers.append(key, v);
    } else if (typeof value === "string") {
      headers.set(key, value);
    }
  }

  const method = req.method ?? "GET";
  const hasBody = method !== "GET" && method !== "HEAD";
  const init: RequestInit & { duplex?: "half" } = { method, headers };
  if (hasBody) {
    init.body = Readable.toWeb(req) as ReadableStream;
    init.duplex = "half";
  }

  const response = await ssr(new Request(url, init));

  res.statusCode = response.status;
  response.headers.forEach((v, k) => res.setHeader(k, v));
  if (response.body) {
    const reader = response.body.getReader();
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      res.write(Buffer.from(value));
    }
  }
  res.end();
}
